"""The case file.

Shape matters here for a reason that is not technical. A business acting against an
impersonator may end up showing this to a registrar, a payment processor, or a court, and the
strength of that case is the strength of its record. So actions are append-only, every finding
carries the search that produced it, and nothing is silently overwritten.

Mirrored one-to-one by the Xano tables in docs/XANO.md. This module is the contract; Xano is
the deployment of it.
"""
from __future__ import annotations

import json
import uuid
from dataclasses import dataclass, field, asdict
from datetime import date, datetime, timezone
from enum import Enum
from pathlib import Path
from typing import Iterable


def _uid() -> str:
    return uuid.uuid4().hex[:12]


def _now() -> str:
    return datetime.now(timezone.utc).isoformat(timespec="seconds")


class Kind(str, Enum):
    LOOKALIKE = "lookalike"      # a domain generated by variants.py
    IMPOSTOR = "impostor"        # something already ranking for the brand that isn't the brand
    LISTING = "listing"          # a local/marketplace listing using the name


class Status(str, Enum):
    """A finding is a suspicion until a person says otherwise. Accusing an unrelated business
    of impersonation is a real harm, so nothing acts on PENDING."""
    PENDING = "pending"
    HOSTILE = "hostile"          # confirmed impersonation
    HARMLESS = "harmless"        # unrelated, or legitimately someone else's
    OURS = "ours"                # already owned by the business


class Verb(str, Enum):
    SWEEP = "sweep"              # generate variants + check availability
    SEARCH = "search"            # SerpApi: who is ranking for this brand
    TRIAGE = "triage"            # a human decision on a finding
    DEFEND = "defend"            # register a dangerous free variant
    REDIRECT = "redirect"        # point a held domain at the real site via DNS


@dataclass
class Case:
    business_name: str
    domain: str                            # the real one, the thing being impersonated
    owner_email: str
    anchors: list[str] = field(default_factory=list)   # town, trade -- sharpens the search
    id: str = field(default_factory=_uid)
    created_at: str = field(default_factory=_now)


@dataclass
class Finding:
    """A domain or listing that might be impersonating the business."""
    case_id: str
    kind: Kind
    label: str
    url: str
    source: str                            # the search or sweep that produced this
    snippet: str = ""
    technique: str = ""                    # for lookalikes: why this variant is dangerous
    registered: bool | None = None         # None until availability is known
    risk: int = 0                          # 0-100, see triage.score
    status: Status = Status.PENDING
    decided_by: str | None = None
    decided_at: str | None = None
    id: str = field(default_factory=_uid)


@dataclass
class Held:
    """A lookalike the business now owns, and where it points."""
    case_id: str
    name: str
    redirects_to: str | None = None
    source: str = "unknown"
    acquired_at: str | None = None
    id: str = field(default_factory=_uid)


@dataclass(frozen=True)
class Action:
    """Append-only. Never updated, never deleted -- this is the account of what was done."""
    case_id: str
    verb: Verb
    target: str
    actor: str
    detail: dict
    dry_run: bool
    result: str
    id: str = field(default_factory=_uid)
    at: str = field(default_factory=_now)


class Store:
    """A JSON-backed implementation of the Xano contract, so the console runs with no keys.
    The Xano adapter satisfies the same five methods against the tables in docs/XANO.md."""

    def __init__(self, path: Path):
        self.path = Path(path)
        self._db = {"cases": [], "findings": [], "held": [], "actions": []}
        if self.path.exists():
            self._db = json.loads(self.path.read_text())

    def _flush(self) -> None:
        self.path.parent.mkdir(parents=True, exist_ok=True)
        self.path.write_text(json.dumps(self._db, indent=2, default=str))

    # --- writes ---------------------------------------------------------------
    def add_case(self, e: Case) -> Case:
        self._db["cases"].append(asdict(e)); self._flush(); return e

    def add_findings(self, cs: Iterable[Finding]) -> list[Finding]:
        cs = list(cs)
        # Scoped to the case, matching the unique index on (case_id, url) in docs/XANO.md.
        # Deduping on url alone made a second case for the same business return nothing --
        # the local store silently disagreeing with the documented Xano schema.
        seen = {(c["case_id"], c["url"]) for c in self._db["findings"]}
        fresh = [c for c in cs if (c.case_id, c.url) not in seen]
        self._db["findings"].extend(asdict(c) for c in fresh)
        self._flush()
        return fresh

    def decide(self, candidate_id: str, status: Status, actor: str) -> dict:
        for c in self._db["findings"]:
            if c["id"] == candidate_id:
                c["status"] = status.value
                c["decided_by"] = actor
                c["decided_at"] = _now()
                self._flush()
                return c
        raise KeyError(candidate_id)

    def upsert_held(self, d: Held) -> Held:
        for row in self._db["held"]:
            if row["case_id"] == d.case_id and row["name"] == d.name:
                row.update({k: v for k, v in asdict(d).items() if k != "id" and v is not None})
                self._flush()
                return d
        self._db["held"].append(asdict(d)); self._flush(); return d

    def log(self, a: Action) -> Action:
        self._db["actions"].append(asdict(a)); self._flush(); return a

    # --- reads ----------------------------------------------------------------
    def findings(self, case_id: str, status: Status | None = None) -> list[dict]:
        rows = [c for c in self._db["findings"] if c["case_id"] == case_id]
        return [c for c in rows if status is None or c["status"] == status.value]

    def held(self, case_id: str) -> list[dict]:
        return [d for d in self._db["held"] if d["case_id"] == case_id]

    def actions(self, case_id: str) -> list[dict]:
        return [a for a in self._db["actions"] if a["case_id"] == case_id]

    def case(self, case_id: str) -> dict:
        for e in self._db["cases"]:
            if e["id"] == case_id:
                return e
        raise KeyError(case_id)
